### ISSUE TITLE
Problem with DiscordSRV

### ISSUE THREAD

**Issue by auremarc** [LeonMangler/PremiumVanishAPI#4]
>.... [02:52:26 INFO]: [PremiumVanish] Message:
>.... [02:52:26 INFO]: [PremiumVanish] Information for reporting an issue
>.... [02:52:26 INFO]: [PremiumVanish] General information:
>.... [02:52:26 INFO]: [PremiumVanish] ServerVersion: git-Paper-468 (MC: 1.16.5)
>.... [02:52:26 INFO]: [PremiumVanish] PluginVersion: 2.6.6
>.... [02:52:26 INFO]: [PremiumVanish] ServerPlugins: PlaceholderAPI v2.10.9, PermissionsEx v1.23.4, CMILib v1.0.0.2, Vault v1.7.3-b${env.TRAVIS_BUILD_NUMBER}, BannerBoard v1.11.5, Votifier v2.7.1, Multiverse-Core v2.5-b719, ProtocolLib v4.5.1, WorldEdit v7.2.2+fc3c499, eZProtector v1.1.0, DeluxeMenus v1.13.3-Release, WorldGuard v7.0.4+f7ff984, Citizens v2.0.27-SNAPSHOT (build 2247), VotingPlugin v6.0.4, DiscordSRV v1.21.3, CMI v8.8.1.5, BungeeTabListPlus v3.4.2, CMIPaperLib v1.0.0,
>.... [02:52:26 INFO]: [PremiumVanish] Settings:
>.... [02:52:26 INFO]: [PremiumVanish] MsgsVersion: 2.6.3
>.... [02:52:26 INFO]: [PremiumVanish] Settings: ||InvisibilityFeatures.NightVisionEffect>true||InvisibilityFeatures.DisableDamage>true||InvisibilityFeatures.DisableHunger>true||InvisibilityFeatures.DisableMobTarget>true||InvisibilityFeatures.DisablePreventBlockPlacement>true||InvisibilityFeatures.RequireChatMessageSuffix>deny||InvisibilityFeatures.OpenChestsSilently>true||InvisibilityFeatures.OpenPlayerInventoryOnRightClick>true||InvisibilityFeatures.AllowSpectatorInventoryEdit>true||InvisibilityFeatures.DisablePressurePlates>true||InvisibilityFeatures.DisablePush>false||InvisibilityFeatures.HideInTablist>true||InvisibilityFeatures.ResetShowInTabOnQuit>true||InvisibilityFeatures.HideInGame>true||InvisibilityFeatures.HideSpectatorMode>true||InvisibilityFeatures.DefaultPickUpItemsOption>false||InvisibilityFeatures.VanishCommands>[]||InvisibilityFeatures.ReappearCommands>[]||InvisibilityFeatures.CustomCommandMessages./examplemsg1 <vanished>>&cPlayer not found||InvisibilityFeatures.DisableEnvironmentalDamageAfterReappear>5||InvisibilityFeatures.SetSleepingIgnored>true||InvisibilityFeatures.SwitchGamemode>true||VanishStateFeatures.AutoVanishOnJoin>false||VanishStateFeatures.ReappearOnWorldChange>false||VanishStateFeatures.ReappearOnQuit>false||VanishStateFeatures.CheckPermissionOnWorldChange>true||VanishStateFeatures.CheckPermissionOnQuit>true||VanishStateFeatures.CheckPermissionOnLogin>true||IndicationFeatures.LayeredPermissions.EnableSeePermission>true||IndicationFeatures.LayeredPermissions.LayeredSeeAndUsePermissions>true||IndicationFeatures.LayeredPermissions.MaxLevel>100||IndicationFeatures.LayeredPermissions.HideInvisibleInCommands>true||IndicationFeatures.LayeredPermissions.AlternatePermissionChecking>false||IndicationFeatures.LayeredPermissions.StrictSetLevelPermissionChecking>false||IndicationFeatures.MarkVanishedPlayersAsSpectators>true||IndicationFeatures.MarkVanishedPlayersWithGlow>false||SurvivalFriendlyFeatures.Fly.Enable>true||SurvivalFriendlyFeatures.Fly.DisableOnReappear>true||SurvivalFriendlyFeatures.GameMode.ChangeToOnVanish.Default>KEEP||SurvivalFriendlyFeatures.GameMode.ChangeToOnReappear.Default>KEEP||SurvivalFriendlyFeatures.GameMode.ReApplyGameModeChangeOnWorldChange>true||SurvivalFriendlyFeatures.GameMode.ReApplyGameModeChangeOnJoin>true||SurvivalFriendlyFeatures.GameMode.AlwaysApplyOnJoinVanished>true||SurvivalFriendlyFeatures.Location.TeleportBackOnReappear>true||MessageOptions.MessagesOnVanishReappear.BroadcastMessageOnVanish>true||MessageOptions.MessagesOnVanishReappear.BroadcastMessageOnReappear>true||MessageOptions.MessagesOnVanishReappear.AdminsGetAnnouncementInstead>false||MessageOptions.MessagesOnVanishReappear.DontSendFakeJoinQuit>false||MessageOptions.MessagesOnVanishReappear.DontSendAdminAnnouncements>true||MessageOptions.MessagesOnJoinQuit.HideRealJoinQuitMessages>true||MessageOptions.MessagesOnJoinQuit.AnnounceRealJoinQuit>true||MessageOptions.MessagesOnJoinQuit.ReappearOnQuitHideMessage>true||MessageOptions.MessagesOnJoinQuit.RemindVanishedOnJoin>true||MessageOptions.DisplayActionBar>true||RestrictiveOptions.PreventBlockBreaking>true||RestrictiveOptions.PreventBlockPlacing>true||RestrictiveOptions.PreventBlockUse>true||RestrictiveOptions.PreventInteract>true||RestrictiveOptions.PreventHittingEntities>true||RestrictiveOptions.PreventDroppingItems>true||RestrictiveOptions.PreventModifyingOwnInventory>false||RestrictiveOptions.PreventModifyingOtherInventory>false||RestrictiveOptions.PreventSpectatorTeleporting>false||RestrictiveOptions.PreventCreativeItemGrab>true||RestrictiveOptions.HiddenCoordinates>false||RestrictiveOptions.Commands.VanishedCommandBlacklist>[examplecommand123test]||RestrictiveOptions.Commands.UseAsWhitelist>false||ExternalInvisibility.ServerList.AdjustAmountOfOnlinePlayers>true||ExternalInvisibility.ServerList.AdjustListOfLoggedInPlayers>true||ScoreboardOptions.Enable>true||ScoreboardOptions.Permission>false||ScoreboardOptions.Sidebar.ScoreboardHeader>&b» &f&lMenu d'invisibilité &b«||ScoreboardOptions.Sidebar.Lines>[, &fCible : &b%target% %locked%, , &fPing : &b%plain_ping%, &fTPS : &b%plain_tps%, , &fHeure : &b%server_time_HH:mm:ss dd/MM/yyyy%]||ScoreboardOptions.Sidebar.InfoUpdateInterval>20||ScoreboardOptions.Targeting.AutoTargetClosestPlayer>false||ScoreboardOptions.Targeting.TargetOnRightClick>true||ScoreboardOptions.Targeting.TargetGlows>true||HookOptions.EnableEssentialsHook>true||HookOptions.EnableDynmapHook>false||HookOptions.DynmapSendJoinLeaveMessages>false||HookOptions.EnableLibsDisguisesHook>true||HookOptions.EnableDisguiseCraftHook>true||HookOptions.EnableTrailGUIHook>true||HookOptions.EnableSuperTrailsHook>true||HookOptions.EnablePlaceholderAPIHook>true||HookOptions.EnableMVdWPlaceholderAPIHook>true||HookOptions.EnableCitizensHook>true||HookOptions.EnableCustomParticleEffectsHook>true||HookOptions.EnableNametagEditHook>true||HookOptions.EnableFeatherBoardHook>true||HookOptions.EnableEnjinMinecraftPluginHook>true||HookOptions.EnableCMIHook>true||InvisibilityMethod.PlayerHider>Hybrid||InvisibilityMethod.Advanced.DisabledInvisibilityModules>[ScoreboardTeam, TabComplete]||CompatibilityOptions.PlayerJoinEventPriority>HIGH||CompatibilityOptions.PlayerQuitEventPriority>HIGH||CompatibilityOptions.AsyncPlayerChatEventPriority>HIGH||CompatibilityOptions.PlayerCommandPreprocessEventPriority>HIGH||MiscellaneousOptions.Bungeecord.Enable>true||MiscellaneousOptions.Bungeecord.Ip>178.32.113.35||MiscellaneousOptions.Bungeecord.Port>3306||MiscellaneousOptions.Bungeecord.CustomURI>||MiscellaneousOptions.Bungeecord.User>****||MiscellaneousOptions.Bungeecord.Password>****||MiscellaneousOptions.Bungeecord.Database>minesr_65458||MiscellaneousOptions.Bungeecord.BasicDatabaseConnector>false||MiscellaneousOptions.AntiSpam.AntiSpamCheck>true||MiscellaneousOptions.AntiSpam.AntiSpamDelay>1||MiscellaneousOptions.AntiSpam.AlwaysCoverVanish>true||MiscellaneousOptions.Command.Name>pv||MiscellaneousOptions.Command.Aliases>[premiumvanish, v, vanish]||MiscellaneousOptions.Command.ForceOverrideForAliases>true||MiscellaneousOptions.UpdateChecker.Enable>true||MiscellaneousOptions.UpdateChecker.NotifyAdmins>true||ConfigVersion>2.6.0||
>.... [02:52:26 INFO]: [PremiumVanish] StackTrace:
>.... [02:52:26 WARN]: java.lang.RuntimeException: Information for reporting an issue
>.... [02:52:26 WARN]: at de.myzelyam.premiumvanish.bukkit.utils.ExceptionLogger.logException(ExceptionLogger.java:28)
>.... [02:52:26 WARN]: at de.myzelyam.premiumvanish.bukkit.PremiumVanish.logException(PremiumVanish.java:327)
>.... [02:52:26 WARN]: at de.myzelyam.premiumvanish.bukkit.commands.subcommands.PrintStacktrace.execute(PrintStacktrace.java:20)
>.... [02:52:26 WARN]: at de.myzelyam.premiumvanish.bukkit.commands.SubCommandMgr.execute(SubCommandMgr.java:242)
>.... [02:52:26 WARN]: at de.myzelyam.premiumvanish.bukkit.commands.FlexibleCommand.execute(FlexibleCommand.java:63)
>.... [02:52:26 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
>.... [02:52:26 WARN]: at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:806)
>.... [02:52:26 WARN]: at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2021)
>.... [02:52:26 WARN]: at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1832)
>.... [02:52:26 WARN]: at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1785)
>.... [02:52:26 WARN]: at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47)
>.... [02:52:26 WARN]: at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5)
>.... [02:52:26 WARN]: at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
>.... [02:52:26 WARN]: at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
>.... [02:52:26 WARN]: at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
>.... [02:52:26 WARN]: at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
>.... [02:52:26 WARN]: at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
>.... [02:52:26 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1133)
>.... [02:52:26 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1126)
>.... [02:52:26 WARN]: at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
>.... [02:52:26 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1087)
>.... [02:52:26 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1001)
>.... [02:52:26 WARN]: at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174)
>.... [02:52:26 WARN]: at java.base/java.lang.Thread.run(Thread.java:834)
>.... [02:52:26 INFO]: [PremiumVanish] End of information.

**And there is the DiscordSRV plugin message :**

>.... [02:48:36 ERROR]: Could not pass event PostPlayerHideEvent to DiscordSRV v1.21.3
java.lang.NullPointerException: null
at github.scarsz.discordsrv.DiscordSRV.translateMessage(DiscordSRV.java:1845) ~[?:?]
at github.scarsz.discordsrv.DiscordSRV.sendLeaveMessage(DiscordSRV.java:1718) ~[?:?]
at de.myzelyam.premiumvanish.bukkit.hooks.DiscordSRVHook.onVanish(DiscordSRVHook.java:24) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor320.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-468]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-468]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-468]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-468]
at de.myzelyam.premiumvanish.bukkit.visibility.VisibilityChanger.hidePlayer(VisibilityChanger.java:157) ~[?:?]
at de.myzelyam.premiumvanish.bukkit.visibility.VisibilityChanger.hidePlayer(VisibilityChanger.java:53) ~[?:?]
at de.myzelyam.premiumvanish.bukkit.visibility.VisibilityChanger.hidePlayer(VisibilityChanger.java:36) ~[?:?]
at de.myzelyam.premiumvanish.bukkit.commands.SubCommand.hidePlayer(SubCommand.java:33) ~[?:?]
at de.myzelyam.premiumvanish.bukkit.commands.subcommands.VanishSelf.execute(VanishSelf.java:25) ~[?:?]
at de.myzelyam.premiumvanish.bukkit.commands.SubCommandMgr.execute(SubCommandMgr.java:79) ~[?:?]
at de.myzelyam.premiumvanish.bukkit.commands.FlexibleCommand.execute(FlexibleCommand.java:63) ~[?:?]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-468]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:806) ~[patched_1.16.5.jar:git-Paper-468]
at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2021) ~[patched_1.16.5.jar:git-Paper-468]
at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1832) ~[patched_1.16.5.jar:git-Paper-468]
at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1785) ~[patched_1.16.5.jar:git-Paper-468]
at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.5.jar:git-Paper-468]
at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.5.jar:git-Paper-468]
at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.5.jar:git-Paper-468]
at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-468]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-468]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-468]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-468]
at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1133) ~[patched_1.16.5.jar:git-Paper-468]
at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1126) ~[patched_1.16.5.jar:git-Paper-468]
at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-468]
at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1200) ~[patched_1.16.5.jar:git-Paper-468]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:997) ~[patched_1.16.5.jar:git-Paper-468]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.5.jar:git-Paper-468]
at java.lang.Thread.run(Thread.java:834) [?:?]

**Comment by LeonMangler** [comment]
Hey, I don't think this issue is related to the PremiumVanishAPI. It looks like there is an error when PV's DiscordSRV hook tried to use DiscordSRV's own [translateMessage(..)](https://github.com/DiscordSRV/DiscordSRV/blob/master/src/main/java/github/scarsz/discordsrv/DiscordSRV.java#L1845) API to broadcast a fake quit message. Since the error occurs in DiscordSRV's code I can't do much to fix it, I have to rely on their API to work. Please make sure that you're using the latest version of DiscordSRV. You can also disable PV's DiscordSRV hook in the config in case you don't need it.

On a side note and unrelated to the error itself, I've noticed that it says "Could not pass event PostPlayerHideEvent to DiscordSRV", which is wrong since the event was actually registered by PV. I'll fix that inconsistency in the next update.

**Comment by Vankka** [comment]
This is a known issue on our current releases, it's fixed on our snapshots - https://snapshot.discordsrv.com
