### ISSUE TITLE
Players can see vanished people

### ISSUE THREAD

**Issue by Mattrolol** [LeonMangler/PremiumVanishAPI#5]
WhenI vanish in game, other players can use /bal <name> (not the full ign) even with prefix/suffix to check if someone is in vanish. Eg: username: test123
Someone could just type /bal test and it would show them their bal, which tells them that he is in vanish.

**Comment by Mattrolol** [comment]
I also added
    CustomCommandMessages:
      '/bal <vanished>': "&4Error: &cPlayer not found"
      but players can do /bal <prefix> instead.

**Comment by LeonMangler** [comment]
Hey, what plugin is /bal from?
The correct CustomCommandMessages format is:
`'/bal <vanished>': "&4Error: &cPlayer not found"`
<vanished> is the placeholder for a vanished player's name. Please make sure that the indentation is right and that you put it into the spigot-sided PV config, since the /bal command is most likely from a spigot plugin.

**Comment by Mattrolol** [comment]
The /bal plugin is EssentialsX so lets say i'm in vanish and my prefix is owner, players can see if i'm in vanish by doing "/bal owner" If i'm offline and when they use "/bal owner" result will be nothing. But if they use the command while i'm online and vanished they can see result also same method on suffix/nick.

**Comment by LeonMangler** [comment]
Vanished players are hidden in /list, right? I still suggest using the CustomCommandMessages feature to make it output the same message as if you were offline. Please send me your config file if it doesn't work.

**Comment by Mattrolol** [comment]
CustomCommandMessages is useless because you can balance offline players.

**Comment by LeonMangler** [comment]
> players can see if i'm in vanish by doing "/bal owner" If i'm offline and when they use "/bal owner" result will be nothing
How is it different when you are vanished then? Support for Essentials commands doesn't work as well when PlayerHider is set to Interception in the config, so please make sure that's not the case. Other than the CustomCommandMessages feature I don't have much control over Essentials' own commands so I don't think there's much I can do to change its behavior.
