### ISSUE TITLE
VanishAPI set level

### ISSUE THREAD

**Issue by RossRao** [LeonMangler/PremiumVanishAPI#6]
I was just wondering if there was a way to set vanish levels within the API? Any help would be greatly appreciated!

**Comment by LeonMangler** [comment]
There currently isn't an official way to do that but I might add one in the future. In case you just want to use it on your own server then this unofficial way to do it might be of interest:
`          VanishPlayer vanishPlayer = VanishAPI.getPlugin().getVanishPlayer(p);
            vanishPlayer.setUsePermissionLevel(level);

            for (final Player onlinePlayer : Bukkit.getOnlinePlayers()) {
                if (onlinePlayer == p) continue;
                final boolean canSeeNow = VanishAPI.getPlugin().hasPermissionToSee(onlinePlayer, p);
                VanishAPI.getPlugin().visibilityChanger.getHider().setHidden(p, onlinePlayer, !canSeeNow);

                if (canSeeNow && VanishAPI.getPlugin().featureMgr.getFeature(VanishIndication.class) != null) {
                    plugin.getServer().getScheduler().runTaskLater(plugin,
                            () -> VanishAPI.getPlugin().featureMgr.getFeature(VanishIndication.class)
                                    .sendPlayerInfoChangeGameModePacket(onlinePlayer, p, true), 5);
                }
            }`
I've just copied it from the "/pv setlevel" command. You'll need to compile it against PV itself. No guarantee that it'll keep working in future releases though.

**Comment by RossRao** [comment]
Thank you for the help!
